//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimenawebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activities_RefImg
    {
        public int ID_detail { get; set; }
        public string src { get; set; }
        public string ID_customer { get; set; }
        public string ID_category { get; set; }
        public int ID_subcategory { get; set; }
        public int ID_brand { get; set; }
        public string query1 { get; set; }
    }
}
