//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimenawebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BI_Contact_Person
    {
        public string CardCode { get; set; }
        public string Tipo { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Tel1 { get; set; }
        public string Email { get; set; }
        public string Position { get; set; }
        public int Id_Contact { get; set; }
        public string IsBuyer { get; set; }
        public Nullable<int> SlpCode { get; set; }
        public string SlpName { get; set; }
        public string SlpEmail { get; set; }
    }
}
