//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimenawebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BI_Dim_Customer
    {
        public string id_Customer { get; set; }
        public string Customer { get; set; }
        public string SalesRep { get; set; }
        public Nullable<int> CatCommission { get; set; }
        public string Supervisor { get; set; }
        public string AreaSupervisor { get; set; }
        public string ZonaSupervisor { get; set; }
        public string SalesRoute { get; set; }
        public string DeliveryRoute { get; set; }
        public string SalesZone { get; set; }
        public string DeliveryZone { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string Classification { get; set; }
        public string CustomerType { get; set; }
        public string Active { get; set; }
        public Nullable<int> id_SalesRep { get; set; }
        public Nullable<decimal> Budget { get; set; }
        public string VisitDayWA { get; set; }
        public string VisitDayWB { get; set; }
        public Nullable<short> U_VisitFrequency { get; set; }
        public Nullable<int> Frequency { get; set; }
        public string Type { get; set; }
        public string ZipCode { get; set; }
        public string PymntGroup { get; set; }
        public string Warehouses { get; set; }
        public string IsBuyer { get; set; }
        public string StatusCustomer { get; set; }
        public string StatusCustomerName { get; set; }
        public string Address { get; set; }
        public string SalesDay { get; set; }
        public string DeliveryDay { get; set; }
        public string MainTel { get; set; }
        public string MainEmail { get; set; }
        public string Week1 { get; set; }
        public string Week2 { get; set; }
        public string Week3 { get; set; }
        public string Week4 { get; set; }
    }
}
