//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimenawebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BI_Dim_Products
    {
        public string id { get; set; }
        public string Product { get; set; }
        public string Brand_Name { get; set; }
        public Nullable<int> id_subcategory { get; set; }
        public string subcategory_name { get; set; }
        public string id_category { get; set; }
        public string category_name { get; set; }
        public string Vendor { get; set; }
        public Nullable<decimal> LeadTime { get; set; }
        public string BuyUnitMsr { get; set; }
        public Nullable<decimal> NumInBuy { get; set; }
        public string Active { get; set; }
        public string Blocked { get; set; }
        public string Pepperi { get; set; }
        public string CatCommission { get; set; }
        public Nullable<decimal> CommPerc { get; set; }
        public string CodeBars { get; set; }
        public string DSD { get; set; }
        public Nullable<decimal> SRP { get; set; }
    }
}
