//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimenawebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_DROUTE
    {
        public string Code { get; set; }
        public string Name { get; set; }
        public string U_PDay { get; set; }
        public string U_WeekA { get; set; }
        public string U_WeekB { get; set; }
        public string U_Staging { get; set; }
        public string U_PDayB { get; set; }
        public string U_Zone { get; set; }
        public string U_Driver { get; set; }
        public string U_RLeader { get; set; }
        public string U_DelDayA { get; set; }
        public string U_DelDayB { get; set; }
    }
}
