//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimenawebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_DRIVERS
    {
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> U_Salario { get; set; }
        public Nullable<decimal> U_Bono { get; set; }
        public string U_Whs { get; set; }
        public string U_Active { get; set; }
    }
}
