//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimenawebApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbComerciaEntities : DbContext
    {
        public dbComerciaEntities()
            : base("name=dbComerciaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActivitiesM> ActivitiesM { get; set; }
        public virtual DbSet<ActivitiesM_log> ActivitiesM_log { get; set; }
        public virtual DbSet<ActivitiesM_types> ActivitiesM_types { get; set; }
        public virtual DbSet<form_resource_type> form_resource_type { get; set; }
        public virtual DbSet<FormsM> FormsM { get; set; }
        public virtual DbSet<FormsM_details> FormsM_details { get; set; }
        public virtual DbSet<RoutesM> RoutesM { get; set; }
        public virtual DbSet<VisitsM> VisitsM { get; set; }
        public virtual DbSet<VisitsM_representatives> VisitsM_representatives { get; set; }
        public virtual DbSet<Activities_RefImg> Activities_RefImg { get; set; }
        public virtual DbSet<FormsM_detailsTasks> FormsM_detailsTasks { get; set; }
        public virtual DbSet<Tasks> Tasks { get; set; }
    }
}
