//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimenawebApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MatrizComprasEntities : DbContext
    {
        public MatrizComprasEntities()
            : base("name=MatrizComprasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Matriz_Formato> Matriz_Formato { get; set; }
        public virtual DbSet<Purchase_catalog> Purchase_catalog { get; set; }
        public virtual DbSet<view_MatrizMadre> view_MatrizMadre { get; set; }
        public virtual DbSet<Transito_Final> Transito_Final { get; set; }
    }
}
