//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimenawebApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DLI_PROEntities : DbContext
    {
        public DLI_PROEntities()
            : base("name=DLI_PROEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<OCRD> OCRD { get; set; }
        public virtual DbSet<BI_Dim_Customer> BI_Dim_Customer { get; set; }
        public virtual DbSet<UFD1> UFD1 { get; set; }
        public virtual DbSet<BI_Dim_Products> BI_Dim_Products { get; set; }
        public virtual DbSet<ITM1> ITM1 { get; set; }
        public virtual DbSet<Dsd_Products> Dsd_Products { get; set; }
        public virtual DbSet<View_dsd_suggestedinventory> View_dsd_suggestedinventory { get; set; }
        public virtual DbSet<C_DROUTE> C_DROUTE { get; set; }
        public virtual DbSet<C_HELPERS> C_HELPERS { get; set; }
        public virtual DbSet<C_TRUCKS> C_TRUCKS { get; set; }
        public virtual DbSet<C_DRIVERS> C_DRIVERS { get; set; }
        public virtual DbSet<OpenSalesOrders_Details> OpenSalesOrders_Details { get; set; }
        public virtual DbSet<OpenSalesOrders_DetailsUOM> OpenSalesOrders_DetailsUOM { get; set; }
        public virtual DbSet<C_PICKERS> C_PICKERS { get; set; }
        public virtual DbSet<OHEM> OHEM { get; set; }
        public virtual DbSet<OSLP> OSLP { get; set; }
        public virtual DbSet<SalesRep> SalesRep { get; set; }
        public virtual DbSet<Supervisor> Supervisor { get; set; }
        public virtual DbSet<view_cuentascobrarCliente> view_cuentascobrarCliente { get; set; }
        public virtual DbSet<view_ordenesAbiertasDet> view_ordenesAbiertasDet { get; set; }
        public virtual DbSet<view_VendorsData> view_VendorsData { get; set; }
        public virtual DbSet<ITT1> ITT1 { get; set; }
        public virtual DbSet<OITT> OITT { get; set; }
        public virtual DbSet<PlanningUoMInfo> PlanningUoMInfo { get; set; }
        public virtual DbSet<OBIN> OBIN { get; set; }
        public virtual DbSet<BI_Contact_Person> BI_Contact_Person { get; set; }
        public virtual DbSet<OpenSalesOrders> OpenSalesOrders { get; set; }
    
        public virtual ObjectResult<sp_genericInvoice_Result> sp_genericInvoice(string dockey)
        {
            var dockeyParameter = dockey != null ?
                new ObjectParameter("dockey", dockey) :
                new ObjectParameter("dockey", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_genericInvoice_Result>("sp_genericInvoice", dockeyParameter);
        }
    
        public virtual ObjectResult<sp_genericDailyPaymentsCrossDock_Result> sp_genericDailyPaymentsCrossDock(string truck, string date)
        {
            var truckParameter = truck != null ?
                new ObjectParameter("Truck", truck) :
                new ObjectParameter("Truck", typeof(string));
    
            var dateParameter = date != null ?
                new ObjectParameter("Date", date) :
                new ObjectParameter("Date", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_genericDailyPaymentsCrossDock_Result>("sp_genericDailyPaymentsCrossDock", truckParameter, dateParameter);
        }
    
        public virtual ObjectResult<sp_genericInvoiceV2_Result> sp_genericInvoiceV2(string dockey)
        {
            var dockeyParameter = dockey != null ?
                new ObjectParameter("dockey", dockey) :
                new ObjectParameter("dockey", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_genericInvoiceV2_Result>("sp_genericInvoiceV2", dockeyParameter);
        }
    
        public virtual ObjectResult<sp_genericInvoiceV2_kit_Result> sp_genericInvoiceV2_kit(string docEntry, string kitcode)
        {
            var docEntryParameter = docEntry != null ?
                new ObjectParameter("docEntry", docEntry) :
                new ObjectParameter("docEntry", typeof(string));
    
            var kitcodeParameter = kitcode != null ?
                new ObjectParameter("kitcode", kitcode) :
                new ObjectParameter("kitcode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_genericInvoiceV2_kit_Result>("sp_genericInvoiceV2_kit", docEntryParameter, kitcodeParameter);
        }
    }
}
