//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimenawebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dsd_Products
    {
        public string id { get; set; }
        public string Product { get; set; }
        public Nullable<decimal> Price { get; set; }
        public short PriceList { get; set; }
        public Nullable<decimal> SRP { get; set; }
        public string CodeBars { get; set; }
        public string category_name { get; set; }
        public string subcategory_name { get; set; }
        public string DSD { get; set; }
        public string id_category { get; set; }
        public Nullable<int> id_subcategory { get; set; }
    }
}
