//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimenawebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Help_Invoices_Layout
    {
        public string CardCode { get; set; }
        public string CardName { get; set; }
        public int DocNum { get; set; }
        public int DocEntry { get; set; }
        public System.DateTime DocDate { get; set; }
        public System.DateTime DocDueDate { get; set; }
        public int SlpCode { get; set; }
        public string SlpName { get; set; }
        public string BaseRef { get; set; }
        public int BaseType { get; set; }
        public short GroupNum { get; set; }
        public string PymntGroup { get; set; }
        public string ShipToCode { get; set; }
        public string Address2 { get; set; }
        public string PHONE { get; set; }
        public string Comments { get; set; }
        public string TrnspName { get; set; }
        public decimal Volume { get; set; }
        public decimal Weight { get; set; }
        public int U_STOPD { get; set; }
        public string U_ROUTED { get; set; }
        public string U_REGIOND { get; set; }
        public string TreeType { get; set; }
        public string ItemCode { get; set; }
        public string Dscription { get; set; }
        public decimal CalcSRP { get; set; }
        public decimal U_SRP { get; set; }
        public decimal Weight1 { get; set; }
        public string Category { get; set; }
        public string GrupName { get; set; }
        public string ItmsGrpNam { get; set; }
        public string CodeBars { get; set; }
        public string BinLoc { get; set; }
        public string WhsCode { get; set; }
        public decimal Quantity { get; set; }
        public decimal Price { get; set; }
        public decimal UnitPrice { get; set; }
        public string PriceBefDi { get; set; }
        public decimal LineTotal { get; set; }
        public string TotalExpns { get; set; }
        public string UomCode { get; set; }
        public string uniMsr { get; set; }
        public decimal NumPerMsr { get; set; }
        public string TotalBefDisc { get; set; }
        public decimal DiscPrcnt { get; set; }
        public string DiscSum { get; set; }
        public string DocTotal { get; set; }
        public decimal Discount { get; set; }
        public string PROMO { get; set; }
        public string PERC { get; set; }
        public string AMOUNT { get; set; }
        public decimal NormalPrice { get; set; }
        public decimal DiscPer { get; set; }
        public decimal DiscAmount { get; set; }
        public decimal Cases { get; set; }
        public decimal Packs { get; set; }
        public decimal Units { get; set; }
        public decimal Libras { get; set; }
        public int AREA { get; set; }
        public string Storage { get; set; }
        public string Liq { get; set; }
        public decimal TotalPlus { get; set; }
        public decimal TotalNeg { get; set; }
        public string ReturnReason { get; set; }
        public int LineNum { get; set; }
        public int VisOrder { get; set; }
    }
}
