//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimenawebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_Project_products
    {
        public int ID_detail { get; set; }
        public string ItemCode { get; set; }
        public string ItemName { get; set; }
        public int ID_Picker { get; set; }
        public string PickerName { get; set; }
        public int count { get; set; }
        public int ID_project { get; set; }
        public bool Used { get; set; }
        public string Bin_locations { get; set; }
    }
}
