//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimenawebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_Projects_Task
    {
        public int ID_projects_task { get; set; }
        public int ID_binloc { get; set; }
        public string Bin_location { get; set; }
        public System.DateTime creation_date { get; set; }
        public int ID_userEnd { get; set; }
        public string UserName { get; set; }
        public int ID_status { get; set; }
        public string comments { get; set; }
        public System.DateTime end_date { get; set; }
        public int Count { get; set; }
        public bool isselected { get; set; }
        public string ItemCode { get; set; }
        public string ItemName { get; set; }
        public string UoM_code { get; set; }
        public int UoM_entry { get; set; }
        public decimal Quantity { get; set; }
        public string UoM_code2 { get; set; }
        public int UoM_entry2 { get; set; }
        public decimal Quantity2 { get; set; }
        public string UoM_code3 { get; set; }
        public int UoM_entry3 { get; set; }
        public decimal Quantity3 { get; set; }
        public string UoM_code4 { get; set; }
        public int UoM_entry4 { get; set; }
        public decimal Quantity4 { get; set; }
        public decimal Final_quantity { get; set; }
        public int ID_empresa { get; set; }
    }
}
