//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimenawebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_Projects
    {
        public int ID_project { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public System.DateTime Creation_date { get; set; }
        public System.DateTime End_date { get; set; }
        public string IDusers_assigned { get; set; }
        public bool isfinished { get; set; }
        public bool isuploaded { get; set; }
        public int Areas { get; set; }
        public int Max_counts { get; set; }
        public int Error { get; set; }
        public string MensajeError { get; set; }
        public int ID_empresa { get; set; }
    }
}
