//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimenawebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_Projects_BinLoc
    {
        public int ID_binloc { get; set; }
        public int Bin_IDSAP { get; set; }
        public string Bin_location { get; set; }
        public string Warehouse { get; set; }
        public string Aisle { get; set; }
        public string Position { get; set; }
        public string Levelpst { get; set; }
        public string Pallet_position { get; set; }
        public string Type { get; set; }
        public string Area { get; set; }
        public int Internal_sort { get; set; }
        public System.DateTime creation_date { get; set; }
        public int ID_userCreate { get; set; }
        public string UserNameCreate { get; set; }
        public int ID_userAssigned { get; set; }
        public string UserNameAssigned { get; set; }
        public System.DateTime end_date { get; set; }
        public int Actual_counts { get; set; }
        public int Count { get; set; }
        public int ID_status { get; set; }
        public bool isfinished { get; set; }
        public string comments { get; set; }
        public int ID_project { get; set; }
        public int ID_empresa { get; set; }
    }
}
