//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimenawebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITT1
    {
        public string Father { get; set; }
        public int ChildNum { get; set; }
        public int VisOrder { get; set; }
        public string Code { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public string Warehouse { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Currency { get; set; }
        public Nullable<short> PriceList { get; set; }
        public Nullable<decimal> OrigPrice { get; set; }
        public string OrigCurr { get; set; }
        public string IssueMthd { get; set; }
        public string Uom { get; set; }
        public string Comment { get; set; }
        public Nullable<int> LogInstanc { get; set; }
        public string Object { get; set; }
        public string OcrCode { get; set; }
        public string OcrCode2 { get; set; }
        public string OcrCode3 { get; set; }
        public string OcrCode4 { get; set; }
        public string OcrCode5 { get; set; }
        public string PrncpInput { get; set; }
        public string Project { get; set; }
        public Nullable<int> Type { get; set; }
        public string WipActCode { get; set; }
        public Nullable<decimal> AddQuantit { get; set; }
        public string LineText { get; set; }
        public Nullable<int> StageId { get; set; }
    }
}
