//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimenawebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OITT
    {
        public string Code { get; set; }
        public string TreeType { get; set; }
        public Nullable<short> PriceList { get; set; }
        public Nullable<decimal> Qauntity { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string Transfered { get; set; }
        public string DataSource { get; set; }
        public Nullable<short> UserSign { get; set; }
        public Nullable<short> SCNCounter { get; set; }
        public string DispCurr { get; set; }
        public string ToWH { get; set; }
        public string Object { get; set; }
        public Nullable<int> LogInstac { get; set; }
        public Nullable<int> UserSign2 { get; set; }
        public string OcrCode { get; set; }
        public string HideComp { get; set; }
        public string OcrCode2 { get; set; }
        public string OcrCode3 { get; set; }
        public string OcrCode4 { get; set; }
        public string OcrCode5 { get; set; }
        public Nullable<int> UpdateTime { get; set; }
        public string Project { get; set; }
        public Nullable<decimal> PlAvgSize { get; set; }
        public string Name { get; set; }
        public Nullable<int> CreateTS { get; set; }
        public Nullable<int> UpdateTS { get; set; }
    }
}
