//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimenawebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OpenSalesOrders
    {
        public Nullable<System.DateTime> SODate { get; set; }
        public int NumSO { get; set; }
        public string PepperiNum { get; set; }
        public string CardCode { get; set; }
        public string CustomerName { get; set; }
        public string Printed { get; set; }
        public string DeliveryRoute { get; set; }
        public Nullable<decimal> TotalSO { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
        public Nullable<decimal> GrossProfit { get; set; }
        public Nullable<decimal> GProfitPer { get; set; }
        public Nullable<decimal> TotalInvoice { get; set; }
        public Nullable<decimal> OpenAmount { get; set; }
        public string SalesPerson { get; set; }
        public string Classification { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> IDSalesPerson { get; set; }
        public string BonifPendientes { get; set; }
    }
}
