//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimenawebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase_catalog
    {
        public int ID_catalog { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public Nullable<double> FactorCompra { get; set; }
        public Nullable<double> FactorCompra_quiebre { get; set; }
        public Nullable<double> Politica_cobertura { get; set; }
        public string Comentarios { get; set; }
        public string Prop01 { get; set; }
        public string Prop02 { get; set; }
        public string Prop03 { get; set; }
        public Nullable<double> FactorUnidadCompra { get; set; }
        public Nullable<double> Costo { get; set; }
    }
}
