//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimenawebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseData_product
    {
        public int ID_detail { get; set; }
        public string ItemCode { get; set; }
        public string Description { get; set; }
        public string Vendor { get; set; }
        public string Brand { get; set; }
        public string Category { get; set; }
        public string Subcategory { get; set; }
        public int ID_purchaseData { get; set; }
        public int SourceSel { get; set; }
        public decimal Forecast1_source1 { get; set; }
        public decimal Forecast2_source1 { get; set; }
        public decimal Forecast3_source1 { get; set; }
        public decimal Forecast4_source1 { get; set; }
        public decimal Forecast5_source1 { get; set; }
        public decimal Forecast1_source2 { get; set; }
        public decimal Forecast2_source2 { get; set; }
        public decimal Forecast3_source2 { get; set; }
        public decimal Forecast4_source2 { get; set; }
        public decimal Forecast5_source2 { get; set; }
        public decimal Forecast1_source3 { get; set; }
        public decimal Forecast2_source3 { get; set; }
        public decimal Forecast3_source3 { get; set; }
        public decimal Forecast4_source3 { get; set; }
        public decimal Forecast5_source3 { get; set; }
        public System.DateTime Last_update { get; set; }
        public string Comments { get; set; }
        public Nullable<int> Forecast1_source1_period { get; set; }
        public Nullable<int> Forecast2_source1_period { get; set; }
        public Nullable<int> Forecast3_source1_period { get; set; }
        public Nullable<int> Forecast4_source1_period { get; set; }
        public Nullable<int> Forecast5_source1_period { get; set; }
        public Nullable<int> Forecast1_source1_year { get; set; }
        public Nullable<int> Forecast2_source1_year { get; set; }
        public Nullable<int> Forecast3_source1_year { get; set; }
        public Nullable<int> Forecast4_source1_year { get; set; }
        public Nullable<int> Forecast5_source1_year { get; set; }
        public Nullable<decimal> Baseline1 { get; set; }
        public Nullable<decimal> Baseline2 { get; set; }
        public Nullable<decimal> Baseline3 { get; set; }
        public Nullable<decimal> Baseline4 { get; set; }
        public Nullable<decimal> Baseline5 { get; set; }
    }
}
