//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimenawebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase_data
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Purchase_data()
        {
            this.Purchase_data_details = new HashSet<Purchase_data_details>();
        }
    
        public int ID_purchaseData { get; set; }
        public System.DateTime Date_data { get; set; }
        public System.DateTime Date_create { get; set; }
        public int User_create { get; set; }
        public string Providers { get; set; }
        public string Categories { get; set; }
        public string SubCategories { get; set; }
        public string Brands { get; set; }
        public string query1 { get; set; }
        public string query2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Purchase_data_details> Purchase_data_details { get; set; }
    }
}
