//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimenawebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseData_byReps
    {
        public int ID_detail { get; set; }
        public string ItemCode { get; set; }
        public string Description { get; set; }
        public int ID_purchaseData { get; set; }
        public decimal Forecast1_source2 { get; set; }
        public decimal Forecast2_source2 { get; set; }
        public decimal Forecast3_source2 { get; set; }
        public decimal Forecast4_source2 { get; set; }
        public decimal Forecast5_source2 { get; set; }
        public int ID_user { get; set; }
        public System.DateTime Last_update { get; set; }
        public string Period { get; set; }
        public string Year { get; set; }
    }
}
