//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimenawebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase_dataHistory
    {
        public int ID_detail { get; set; }
        public string ItemCode { get; set; }
        public string Description { get; set; }
        public decimal newValue { get; set; }
        public int periodo { get; set; }
        public int year { get; set; }
        public int ID_purchaseData { get; set; }
        public System.DateTime Last_update { get; set; }
        public int source { get; set; }
        public int ID_user { get; set; }
        public string Username { get; set; }
    }
}
