//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimenawebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supervisor
    {
        public int id_Supervisor { get; set; }
        public string Supervisor_Name { get; set; }
        public string Zone { get; set; }
        public string Area { get; set; }
        public string Active { get; set; }
    }
}
