//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimenawebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_LogCon
    {
        public int ID_log { get; set; }
        public int ID_User { get; set; }
        public string IP { get; set; }
        public string Hostname { get; set; }
        public string TypeH { get; set; }
        public string Continent_Name { get; set; }
        public string Country_Code { get; set; }
        public string Country_Name { get; set; }
        public string Region_Code { get; set; }
        public string Region_Name { get; set; }
        public string City { get; set; }
        public string Lat { get; set; }
        public string Long { get; set; }
        public System.DateTime date { get; set; }
        public int ID_Company { get; set; }
    }
}
