//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimenawebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Autorizaciones
    {
        public int ID_detalle { get; set; }
        public int DocNum { get; set; }
        public string ItemCode { get; set; }
        public string Producto { get; set; }
        public string CodUOM { get; set; }
        public string UOM { get; set; }
        public decimal Cantidad { get; set; }
        public decimal PrecioPedido { get; set; }
        public decimal NuevoPrecio { get; set; }
        public int Estado { get; set; }
        public string DocNumSAP { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public System.DateTime FechaValidacion { get; set; }
        public Nullable<int> LineNum { get; set; }
        public decimal PrecioMin { get; set; }
    }
}
