//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimenawebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_CreditsRequest
    {
        public int ID_creditRequest { get; set; }
        public string ItemCode { get; set; }
        public string ItemName { get; set; }
        public string UoMCode { get; set; }
        public string Request_reason { get; set; }
        public int Quantity { get; set; }
        public string URL_image { get; set; }
        public bool Validated { get; set; }
        public string DocNumSAP { get; set; }
        public int IDRequest_reason { get; set; }
        public System.DateTime dateCreate { get; set; }
        public System.DateTime dateValidate { get; set; }
        public int userValidate { get; set; }
        public string userValidateName { get; set; }
        public int userCreate { get; set; }
        public string userCreateName { get; set; }
        public string CardCode { get; set; }
        public string CardName { get; set; }
        public int estado { get; set; }
        public string comments { get; set; }
        public int LineNum { get; set; }
        public string UoMEntry { get; set; }
        public string URL_image2 { get; set; }
        public string ItemCodeReturn { get; set; }
        public string ItemNameReturn { get; set; }
    }
}
