//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimenawebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_customerscontacts
    {
        public int ID_contact { get; set; }
        public string CardCode { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public string Telephone { get; set; }
        public string Email { get; set; }
        public string Position { get; set; }
        public int Error { get; set; }
        public string ErrorMessage { get; set; }
        public string DocEntry { get; set; }
        public int IDSAP { get; set; }
        public int Accion { get; set; }
        public Nullable<System.DateTime> creationdate { get; set; }
    }
}
