//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimenawebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_InventoryTRDSD
    {
        public int ID_InventoryDSD { get; set; }
        public System.DateTime Date { get; set; }
        public int ID_User { get; set; }
        public string User_name { get; set; }
        public int ID_Company { get; set; }
        public string docNum_SAP { get; set; }
    }
}
