//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimenawebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_logContainers
    {
        public int ID_reg { get; set; }
        public string ID_container { get; set; }
        public string Container { get; set; }
        public string Whs { get; set; }
        public string AssignerUser { get; set; }
        public string ReceivedUser { get; set; }
        public System.DateTime DateAssigned { get; set; }
        public System.DateTime DateReceived { get; set; }
        public string Barcode { get; set; }
        public string Route { get; set; }
        public string Driver { get; set; }
        public string Truck { get; set; }
        public bool inRoute { get; set; }
        public int ID_Route { get; set; }
        public int Status { get; set; }
        public string Comments { get; set; }
        public string Img { get; set; }
    }
}
