//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimenawebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_MaestroPorcentajes
    {
        public int ID_detail { get; set; }
        public Nullable<double> id_brand { get; set; }
        public string Brand_Name { get; set; }
        public string id_category { get; set; }
        public string category_name { get; set; }
        public Nullable<double> id_subcategory { get; set; }
        public string subcategory_name { get; set; }
        public Nullable<double> min_porc { get; set; }
        public Nullable<bool> updated { get; set; }
    }
}
