//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimenawebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_PreOrdersDetailsDSD
    {
        public int ID_Details { get; set; }
        public string ID_Product { get; set; }
        public string Product_Name { get; set; }
        public int Units { get; set; }
        public string ReturnReasonID { get; set; }
        public string ReturnReasonName { get; set; }
        public decimal Price { get; set; }
        public decimal SRP { get; set; }
        public string UPC { get; set; }
        public decimal Total { get; set; }
        public int ID_OrderDSD { get; set; }
        public string GroupDsd { get; set; }
    }
}
