//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimenawebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_PlanningSO
    {
        public int ID_salesorder { get; set; }
        public string SAP_docnum { get; set; }
        public System.DateTime SAP_docdate { get; set; }
        public string ID_customer { get; set; }
        public string Customer_name { get; set; }
        public string ID_rep { get; set; }
        public string Rep_name { get; set; }
        public string ID_SAPRoute { get; set; }
        public decimal Amount { get; set; }
        public bool isfinished { get; set; }
        public string query1 { get; set; }
        public string query2 { get; set; }
        public decimal query3 { get; set; }
        public int ID_Route { get; set; }
        public string DocEntry { get; set; }
        public string query4 { get; set; }
        public string query5 { get; set; }
        public string Weight { get; set; }
        public string Volume { get; set; }
        public string Printed { get; set; }
        public string Remarks { get; set; }
        public System.DateTime DateCheckIn { get; set; }
        public System.DateTime DateCheckOut { get; set; }
        public int ID_userValidate { get; set; }
        public string Warehouse { get; set; }
        public int QC_count { get; set; }
        public int Transferred { get; set; }
        public string MensajeError { get; set; }
        public int Error { get; set; }
    
        public virtual Tb_Planning Tb_Planning { get; set; }
    }
}
