//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimenawebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Planning_extra
    {
        public int ID_detail { get; set; }
        public string Description { get; set; }
        public decimal Value { get; set; }
        public string query1 { get; set; }
        public int ID_Route { get; set; }
    }
}
