//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimenawebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_planning_print
    {
        public int ID_detail { get; set; }
        public bool IsRoute { get; set; }
        public string Doc_key { get; set; }
        public bool Printed { get; set; }
        public string Module { get; set; }
        public Nullable<System.DateTime> Created_on { get; set; }
        public Nullable<System.DateTime> Printed_on { get; set; }
        public Nullable<int> ID_user { get; set; }
    }
}
