//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimenawebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Planning
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_Planning()
        {
            this.Tb_PlanningSO = new HashSet<Tb_PlanningSO>();
        }
    
        public int ID_Route { get; set; }
        public string Route_name { get; set; }
        public string ID_driver { get; set; }
        public string Driver_name { get; set; }
        public string ID_routeleader { get; set; }
        public string Routeleader_name { get; set; }
        public string ID_truck { get; set; }
        public string Truck_name { get; set; }
        public System.DateTime Departure { get; set; }
        public bool isfinished { get; set; }
        public string ID_SAPRoute { get; set; }
        public string query1 { get; set; }
        public string query2 { get; set; }
        public decimal query3 { get; set; }
        public System.DateTime Date { get; set; }
        public bool Invoiced { get; set; }
        public System.DateTime DateCheckIn { get; set; }
        public System.DateTime DateCheckOut { get; set; }
        public int ID_userValidate { get; set; }
        public string Warehouse { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_PlanningSO> Tb_PlanningSO { get; set; }
    }
}
