//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimenawebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Resources
    {
        public int ID_Resource { get; set; }
        public string Description { get; set; }
        public string Url { get; set; }
        public System.DateTime Last_Update { get; set; }
        public int ID_User { get; set; }
        public int ID_ResourceType { get; set; }
        public int ID_Company { get; set; }
    
        public virtual Sys_Companies Sys_Companies { get; set; }
        public virtual Sys_Users Sys_Users { get; set; }
    }
}
