//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimenawebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_registroBolsa
    {
        public int ID_regBolsa { get; set; }
        public int ID_SalesRepresentative { get; set; }
        public string SalesRepresentative { get; set; }
        public decimal Last_value { get; set; }
        public decimal New_value { get; set; }
        public decimal Value { get; set; }
        public System.DateTime Date { get; set; }
        public string AssignedBy { get; set; }
        public int AssignedBy_ID { get; set; }
        public bool Active { get; set; }
        public string Comments { get; set; }
        public int Type { get; set; }
    }
}
