//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimenawebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transito_Final
    {
        public string ProdCodigo { get; set; }
        public int NumTransito { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public string DiaSemana { get; set; }
        public Nullable<double> DifSemanas { get; set; }
        public Nullable<int> NumFactura { get; set; }
        public Nullable<int> CantCajas { get; set; }
        public string FormulaDia { get; set; }
        public Nullable<double> CoberturaSemanal { get; set; }
    }
}
