//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimenawebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_dsd_suggestedinventory
    {
        public string ItemCode { get; set; }
        public string ItemName { get; set; }
        public string CodeBars { get; set; }
        public string WhsCode { get; set; }
        public string QryGroup8 { get; set; }
        public Nullable<decimal> OnHand { get; set; }
        public Nullable<decimal> MinStock { get; set; }
        public Nullable<decimal> MaxStock { get; set; }
        public Nullable<decimal> Request { get; set; }
        public string WhsName { get; set; }
    }
}
