//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimenawebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_ordenesAbiertasDet
    {
        public int LineNum { get; set; }
        public string U_BinLocation { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public string UomCode { get; set; }
        public Nullable<int> UomEntry { get; set; }
        public Nullable<decimal> InvQty { get; set; }
        public Nullable<decimal> NumPerMsr { get; set; }
        public string ItemCode { get; set; }
        public string ItemName { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string U_Storage { get; set; }
        public int DocNum { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public string CardCode { get; set; }
        public Nullable<int> SlpCode { get; set; }
        public string OpenTotalSO { get; set; }
        public int Blocked { get; set; }
        public string TreeType { get; set; }
        public string NoPepperi { get; set; }
        public string U_DeliveryR { get; set; }
        public string StatusPlanningFlow { get; set; }
        public string Printed { get; set; }
    }
}
