//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimenawebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_MatrizMadre
    {
        public int num { get; set; }
        public string ProdCodigo { get; set; }
        public string ProdNombre { get; set; }
        public double FactorCompra { get; set; }
        public double FactorCompra_quiebre { get; set; }
        public double Politica_cobertura { get; set; }
        public string Marca { get; set; }
        public string SubCategory { get; set; }
        public string Category { get; set; }
        public string ProvCodigo { get; set; }
        public string ProvNombre { get; set; }
        public string UnidadMedidaLetras { get; set; }
        public Nullable<decimal> InventarioEach { get; set; }
        public Nullable<decimal> InventarioCajas { get; set; }
        public double Promedio { get; set; }
        public double Desviacion { get; set; }
        public double Minimo { get; set; }
        public double Maximo { get; set; }
        public double PronosticoPeriodoActual { get; set; }
        public double Promedio_AA { get; set; }
        public double VentaB1 { get; set; }
        public double Variacion { get; set; }
        public decimal TendenciaPeriodoActual { get; set; }
        public double PronosticoSiguiente1 { get; set; }
        public double PronosticoSiguiente2 { get; set; }
        public double PronosticoSiguiente3 { get; set; }
        public double PronosticoSiguiente4 { get; set; }
        public double CoberturaActual { get; set; }
        public double CoberturaProyectada { get; set; }
        public double OTB { get; set; }
        public decimal Pedido { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<System.DateTime> DocumentDate { get; set; }
        public decimal U_TI { get; set; }
        public decimal U_HI { get; set; }
        public decimal PalletsdeOrden { get; set; }
        public double CoberturaProyectadaNume { get; set; }
        public double CoberturaIngresoPO { get; set; }
        public double Costo { get; set; }
        public decimal DescuentoAp { get; set; }
        public decimal DescuentoAn { get; set; }
        public double CostoconDescuento { get; set; }
        public decimal MontoPO { get; set; }
        public string Comentarios { get; set; }
        public double CoberturaProyectadaDeno { get; set; }
        public double VentaF1 { get; set; }
        public double Cobertura_OTB { get; set; }
        public Nullable<int> LeadTime { get; set; }
        public Nullable<int> transito { get; set; }
        public double U_PalletCount { get; set; }
    }
}
